In [6]:
import pandas as pd
import numpy as np
import os

In [7]:
# 配置全局变量


DIR = 'Datasets/Xiamen_data'
# 原始数据地址
origin_dir = DIR+'/origin'

origin_train_data_path = origin_dir+'/train.csv'
origin_train_target_path = origin_dir+'/train_target.csv'
origin_test_data_path = origin_dir+'/test.csv'

# 划分了训练集、验证集、测试集的地址，可以按照某种地区提取特征，置于feature文件夹中
split_dir = DIR+'/split'

train_dir = split_dir+'/train'
train_feature_dir = split_dir+'/train/feature'
train_data = train_dir+'/data.csv'
train_feed = train_dir+'/feed.cvs'
train_target = train_dir+'/target.csv'

validate_dir = split_dir+'/validate'
validate_feature_dir = split_dir+'/validate/feature'
validate_data = validate_dir+'/data.csv'
validate_feed = validate_dir+'/feed.cvs'
validate_target = validate_dir+'/target.csv'

predict_dir = split_dir+'/predict'
predict_feature_dir = split_dir+'/predict/feature'
predict_data = predict_dir+'/data.csv'
predict_feed = predict_dir+'/feed.cvs'
predict_target = predict_dir+'/target.csv'

# 模型存储地址
model_dir = DIR+'/model'

# 提交文件
submit_dir = DIR+'/submit'
submit_feature_dir = submit_dir+'/feature'
submit_data = submit_dir+'/data.csv'
submit_feed = submit_dir+'/feed.cvs'
submit_result = submit_dir+'/result.csv'

In [8]:
origin_train_data=pd.read_csv(origin_train_data_path)
origin_train_data

,id,certId,loanProduct,gender,age,dist,edu,job,lmt,basicLevel,...,highestEdu,linkRela,setupHour,weekday,ncloseCreditCard,unpayIndvLoan,unpayOtherLoan,unpayNormalLoan,5yearBadloan,isNew
0,1,640582,1,2,27,640500,0,8,5.963,3,...,-999,0,9,6,1,0,1,0,0,1
1,2,621023,2,2,25,640600,0,3,6.467,3,...,99,11,6,5,1,0,1,0,0,1
2,3,641283,1,2,37,641200,70,5,0.596,1,...,70,0,1,6,0,0,0,0,0,1
3,4,340821,3,2,29,340821,0,4,6.300,3,...,-999,-999,13,6,1,0,1,0,0,1
4,5,732628,2,2,22,732628,0,2,6.700,2,...,99,11,8,3,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132024,132025,631023,2,2,22,631023,0,4,7.867,2,...,-999,11,12,6,1,0,1,0,0,0
132025,132026,640711,1,2,26,640700,0,4,4.630,1,...,-999,0,11,1,1,0,1,1,0,0
132026,132027,550424,2,2,30,550424,0,16,2.200,3,...,-999,0,7,1,1,0,1,0,0,0
132027,132028,430104,1,1,48,430100,0,4,1.996,1,...,-999,1,17,5,1,0,1,1,0,0
132028,132029,520723,2,2,26,520723,0,16,7.667,3,...,-999,1,17,4,1,1,1,1,0,0

In [9]:
origin_train_target=pd.read_csv(origin_train_target_path)
origin_train_target

            id  target
0            1       0
1            2       0
2            3       0
3            4       0
4            5       0
...        ...     ...
132024  132025       0
132025  132026       0
132026  132027       0
132027  132028       0
132028  132029       0

[132029 rows x 2 columns]

In [10]:
print(origin_train_data['isNew'].sum())

47833

In [14]:
temp=origin_train_data.drop(['id','isNew'],axis=1)
temp

,certId,loanProduct,gender,age,dist,edu,job,lmt,basicLevel,x_0,...,residentAddr,highestEdu,linkRela,setupHour,weekday,ncloseCreditCard,unpayIndvLoan,unpayOtherLoan,unpayNormalLoan,5yearBadloan
0,640582,1,2,27,640500,0,8,5.963,3,0,...,640513,-999,0,9,6,1,0,1,0,0
1,621023,2,2,25,640600,0,3,6.467,3,0,...,621023,99,11,6,5,1,0,1,0,0
2,641283,1,2,37,641200,70,5,0.596,1,0,...,641204,70,0,1,6,0,0,0,0,0
3,340821,3,2,29,340821,0,4,6.300,3,0,...,-999,-999,-999,13,6,1,0,1,0,0
4,732628,2,2,22,732628,0,2,6.700,2,0,...,732628,99,11,8,3,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132024,631023,2,2,22,631023,0,4,7.867,2,0,...,-999,-999,11,12,6,1,0,1,0,0
132025,640711,1,2,26,640700,0,4,4.630,1,0,...,940703,-999,0,11,1,1,0,1,1,0
132026,550424,2,2,30,550424,0,16,2.200,3,0,...,850424,-999,0,7,1,1,0,1,0,0
132027,430104,1,1,48,430100,0,4,1.996,1,0,...,730103,-999,1,17,5,1,0,1,1,0
132028,520723,2,2,26,520723,0,16,7.667,3,0,...,820723,-999,1,17,4,1,1,1,1,0